#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

fly_target=$(bosh int settings.yml --path "/meta/target")
pipeline_name=$(bosh int settings.yml --path "/meta/name")
fly -t $fly_target builds -p $pipeline_name