---
meta:
  name:     (( param "Please name your pipeline" ))
  team:     (( param "Please provide expected concourse team to deploy test pipelines" ))
  pipeline: (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  url:      (( param "Please specify the full url of the target Concourse CI" ))

  image:
    name: (( concat "starkandwayne/" meta.name "-ci" ))
    tag: latest

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch_master: master
    branch_develop: develop
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token to be used for creating github releases (do you have a ci-bot?)" ))

  cf:
    api:              https://api.run.pivotal.io
    skip_cert_check:  false
    username:         (( param "please provide cf.username" ))
    password:         (( param "please provide cf.password" ))
    organization:     (( param "please provide cf.organization" ))
    space-staging:    (( param "please provide cf.space-staging" ))
    space-production: (( param "please provide cf.space-production" ))
    appname:          (( param "appname please"))

  slack:
    webhook:       (( param "Please specify your Slack Incoming Webhook Integration URL" ))
    success_moji:  ":airplane_departure:"
    fail_moji:     ":airplane_arriving:"
    upset_moji:    ":sad_panda:"
    channel:       "#snw-pws-apps"
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
    fail_url: '(( concat "<" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Concourse Failure! " meta.slack.upset_moji ">" ))'
    success_url: '(( concat "<" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Concourse Success " meta.slack.success_moji ">" ))'

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - deploy-production

jobs:
  - name: deploy-production
    public: false
    serial: true
    plan:
      - aggregate:
        - get: app
          resource: app-master
          trigger: true
      - put: cf-push-production
        params:
          manifest: app/manifest-production.yml
          path: app
          current_app_name: (( grab meta.cf.appname ))
          show_app_log: true

resources:
  - name: app-master
    type: git
    source:
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch_master ))
      private_key: (( grab meta.github.private_key ))

  - name: cf-push-production
    type: cf
    source:
      api:             (( grab meta.cf.api ))
      skip_cert_check: (( grab meta.cf.skip_cert_check ))
      username:        (( grab meta.cf.username ))
      password:        (( grab meta.cf.password ))
      organization:    (( grab meta.cf.organization ))
      space:           (( grab meta.cf.space-production ))
